/**
 * Tenetx Lab — Auto-Learning Engine
 *
 * Connects lab -> forge: observes behavioral patterns from lab events,
 * translates them into dimension adjustments, and evolves the forge profile.
 * Creates a closed feedback loop where the harness automatically
 * evolves based on usage data.
 *
 * Conservative by design: small adjustments, high evidence thresholds,
 * exponential moving average smoothing.
 *
 * Module Structure:
 * - Lines 1-90: Imports, constants (thresholds, rates), SYSTEM_INTERNAL_TYPES filter set
 * - Lines 90-145: Storage helpers — atomicWrite, load/save for evolution history, patterns,
 *     last evolve info, last notification
 * - Lines 148-210: Core logic — analyzeEvents (pattern detection + clamping),
 *     applySmoothedAdjustments (EMA + neutral decay)
 * - Lines 212-520: runEvolveCycle — main entry point:
 *     event loading, pattern analysis, v2 Thompson Sampling or v1 EMA,
 *     BKT/correlation/coupled deltas, profile save, transparency notifications
 * - Lines 522-600: shouldAutoLearnRun, tryAutoLearn, hasVectorChanged, regenerateHarnessConfig
 */

import * as path from 'node:path';
import * as os from 'node:os';
import { createLogger } from '../core/logger.js';

const log = createLogger('auto-learn');
import { readEvents } from './store.js';
import { detectPatterns, patternsToDimensionAdjustments } from './pattern-detector.js';
import { track } from './tracker.js';
import type {
  LabEvent,
  DimensionAdjustment,
  EvolutionRecord,
  BehavioralPattern,
  LastEvolveInfo,
} from './types.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LAB_DIR = path.join(os.homedir(), '.compound', 'lab');
const EVOLUTION_HISTORY_PATH = path.join(LAB_DIR, 'evolution-history.json');
const PATTERNS_PATH = path.join(LAB_DIR, 'patterns.json');
const LAST_EVOLVE_PATH = path.join(LAB_DIR, 'last-evolve.json');
export const LAST_NOTIFICATION_PATH = path.join(LAB_DIR, 'last-notification.json');

/** Minimum events required before auto-learning triggers */
const MIN_EVENTS_THRESHOLD = 30;

/** Maximum single adjustment per cycle */
const MAX_DELTA_PER_CYCLE = 0.15;

/** EMA learning rate: new = old + delta * LEARNING_RATE
 * Roberts (1959), Montgomery (2012): α∈[0.05,0.25] for SPC.
 * 0.15 = more conservative for noisy behavioral signals (effective window ~12 cycles) */
const LEARNING_RATE = 0.15;

/** Neutral decay rate: pulls dimensions toward 0.5 when no evidence.
 * Prevents permanent profile drift from temporary behavior changes.
 * 0.02/cycle = ~34 cycles (days) half-life toward neutral (ln(0.5)/ln(0.98) ≈ 34.3).
 * Conservative by design — v1 EMA 경로에서 좁은 유효 범위를 형성하여 급격한 프로필 변경 방지. */
const NEUTRAL_DECAY_RATE = 0.02;

/** Default analysis window: 30 days */
const DEFAULT_WINDOW_DAYS = 30;

/** Minimum hours between auto-learn runs */
const MIN_HOURS_BETWEEN_RUNS = 24;

/**
 * System-internal event types excluded from behavioral pattern analysis.
 * These events are generated by the harness itself, not by user behavior,
 * and would add noise to pattern detection.
 *
 * SYNC: must match non-behavioral types in src/lab/types.ts LabEventType.
 * When adding new compound-* or system types to LabEventType, update this set.
 */
const SYSTEM_INTERNAL_TYPES: ReadonlySet<string> = new Set([
  'synthesis',
  'auto-evolve',
  'session-metrics',  // 시스템 생성 메타데이터 — 사용자 행동이 아니므로 패턴 감지에서 제외
  'compound-injected',
  'compound-reflected',
  'compound-negative',
  'compound-extracted',
  'compound-promoted',
  'compound-demoted',
  'compound-precision',
]);

// ---------------------------------------------------------------------------
// Storage Helpers
// ---------------------------------------------------------------------------

// atomicWrite + safeReadJSON: shared utility
import { atomicWriteJSON, safeReadJSON } from '../hooks/shared/atomic-write.js';
function atomicWrite(filePath: string, data: unknown): void {
  atomicWriteJSON(filePath, data, { pretty: true });
}

// ---------------------------------------------------------------------------
// Evolution History
// ---------------------------------------------------------------------------

export function loadEvolutionHistory(): EvolutionRecord[] {
  return safeReadJSON<EvolutionRecord[]>(EVOLUTION_HISTORY_PATH, []);
}

function saveEvolutionHistory(records: EvolutionRecord[]): void {
  atomicWrite(EVOLUTION_HISTORY_PATH, records);
}

// ---------------------------------------------------------------------------
// Patterns
// ---------------------------------------------------------------------------

export function loadStoredPatterns(): BehavioralPattern[] {
  return safeReadJSON<BehavioralPattern[]>(PATTERNS_PATH, []);
}

function savePatterns(patterns: BehavioralPattern[]): void {
  atomicWrite(PATTERNS_PATH, patterns);
}

// ---------------------------------------------------------------------------
// Last Evolve Info
// ---------------------------------------------------------------------------

export function loadLastEvolveInfo(): LastEvolveInfo | null {
  return safeReadJSON<LastEvolveInfo | null>(LAST_EVOLVE_PATH, null);
}

function saveLastEvolveInfo(info: LastEvolveInfo): void {
  atomicWrite(LAST_EVOLVE_PATH, info);
}

// ---------------------------------------------------------------------------
// Last Notification (dedup guard)
// ---------------------------------------------------------------------------

interface LastNotification {
  timestamp: string;
  /** Sorted dimension keys that changed */
  dimensionKeys: string[];
}

export function loadLastNotification(): LastNotification | null {
  return safeReadJSON<LastNotification | null>(LAST_NOTIFICATION_PATH, null);
}

export function saveLastNotification(info: LastNotification): void {
  atomicWrite(LAST_NOTIFICATION_PATH, info);
}

// ---------------------------------------------------------------------------
// Core Auto-Learning Logic
// ---------------------------------------------------------------------------

/**
 * Analyze events and compute raw dimension adjustments.
 * Does NOT apply smoothing — returns raw pattern-based deltas.
 */
function analyzeEvents(events: LabEvent[]): {
  adjustments: DimensionAdjustment[];
  patterns: BehavioralPattern[];
} {
  const filtered = events.filter(e => !SYSTEM_INTERNAL_TYPES.has(e.type));
  const patterns = detectPatterns(filtered, 0.3);
  const adjustments = patternsToDimensionAdjustments(patterns);

  // Clamp each adjustment to MAX_DELTA_PER_CYCLE
  for (const adj of adjustments) {
    adj.delta = Math.max(-MAX_DELTA_PER_CYCLE, Math.min(MAX_DELTA_PER_CYCLE, adj.delta));
  }

  return { adjustments, patterns };
}

/**
 * Apply smoothing via exponential moving average.
 * new_value = old_value * RETENTION + (old_value + delta) * LEARNING_RATE
 * Which simplifies to: new_value = old_value + delta * LEARNING_RATE
 */
function applySmoothedAdjustments(
  currentVector: Record<string, number>,
  adjustments: DimensionAdjustment[],
): Record<string, number> {
  const result = { ...currentVector };

  // Merge adjustments by dimension (sum deltas for same dimension)
  const mergedDeltas = new Map<string, number>();
  for (const adj of adjustments) {
    const existing = mergedDeltas.get(adj.dimension) ?? 0;
    mergedDeltas.set(adj.dimension, existing + adj.delta);
  }

  // First: apply neutral decay to ALL dimensions (pulls toward 0.5 when no evidence)
  for (const dim of Object.keys(result)) {
    const old = result[dim] ?? 0.5;
    result[dim] = old - (old - 0.5) * NEUTRAL_DECAY_RATE;
  }

  // Then: apply evidence-based adjustments
  for (const [dimension, rawDelta] of mergedDeltas) {
    if (!(dimension in result)) continue;

    // Clamp merged delta
    const clampedDelta = Math.max(-MAX_DELTA_PER_CYCLE, Math.min(MAX_DELTA_PER_CYCLE, rawDelta));

    // Apply EMA smoothing
    const smoothedDelta = clampedDelta * LEARNING_RATE;
    const oldValue = result[dimension] ?? 0.5;
    result[dimension] = Math.max(0, Math.min(1, oldValue + smoothedDelta));
  }

  return result;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Result of an auto-learn cycle */
export interface EvolveResult {
  /** Whether any adjustments were made */
  changed: boolean;
  /** Adjustments computed (may be empty) */
  adjustments: DimensionAdjustment[];
  /** Detected behavioral patterns */
  patterns: BehavioralPattern[];
  /** Previous dimension vector (null if no profile) */
  previousVector: Record<string, number> | null;
  /** New dimension vector (null if dry-run or no profile) */
  newVector: Record<string, number> | null;
  /** Number of events analyzed */
  totalEventsAnalyzed: number;
  /** Reason if no changes */
  reason?: string;
}

/**
 * Run one auto-learning cycle.
 *
 * @param dryRun If true, compute adjustments but don't apply
 * @param windowDays Analysis window (default 30 days)
 * @returns Evolution result with adjustments and patterns
 */
export async function runEvolveCycle(
  dryRun: boolean = false,
  windowDays: number = DEFAULT_WINDOW_DAYS,
): Promise<EvolveResult> {
  try {
    // 1. Load events from the analysis window
    // Guard: windowDays <= 0 is a degenerate case (no valid time range)
    if (windowDays <= 0) {
      return {
        changed: false,
        adjustments: [],
        patterns: [],
        previousVector: null,
        newVector: null,
        totalEventsAnalyzed: 0,
        reason: 'Empty analysis window (windowDays ≤ 0)',
      };
    }
    const sinceMs = Date.now() - windowDays * 24 * 60 * 60 * 1000;
    const events = readEvents(sinceMs);

    if (events.length < MIN_EVENTS_THRESHOLD) {
      return {
        changed: false,
        adjustments: [],
        patterns: [],
        previousVector: null,
        newVector: null,
        totalEventsAnalyzed: events.length,
        reason: `Insufficient events: ${events.length} (minimum: ${MIN_EVENTS_THRESHOLD})`,
      };
    }

    // 2. Detect patterns and compute adjustments
    const { adjustments, patterns } = analyzeEvents(events);

    // Always save detected patterns
    savePatterns(patterns);

    if (adjustments.length === 0) {
      saveLastEvolveInfo({
        timestamp: new Date().toISOString(),
        eventsAnalyzed: events.length,
        adjustmentCount: 0,
        dryRun,
      });
      return {
        changed: false,
        adjustments: [],
        patterns,
        previousVector: null,
        newVector: null,
        totalEventsAnalyzed: events.length,
        reason: 'No actionable patterns detected',
      };
    }

    // 3. Load current forge profile (top-level static import is safe here)
    const { loadForgeProfile, saveForgeProfile, GLOBAL_FORGE_PROFILE } =
      await import('../forge/profile.js');

    const profile = loadForgeProfile();
    if (!profile) {
      return {
        changed: false,
        adjustments,
        patterns,
        previousVector: null,
        newVector: null,
        totalEventsAnalyzed: events.length,
        reason: 'No forge profile found. Run "tenetx forge" first.',
      };
    }

    const previousVector = { ...profile.dimensions };

    if (dryRun) {
      const newVector = applySmoothedAdjustments(previousVector, adjustments);
      return {
        changed: hasVectorChanged(previousVector, newVector),
        adjustments,
        patterns,
        previousVector,
        newVector,
        totalEventsAnalyzed: events.length,
      };
    }

    // 4. Apply adjustments — v2 Thompson Sampling or v1 EMA
    const { loadForgeV2Config, validateForgeV2Config } = await import('./forge-v2-config.js');
    const v2Config = validateForgeV2Config(loadForgeV2Config());
    let newVector: Record<string, number>;

    if (v2Config.thompsonSampling) {
      // === Forge v2: Thompson Sampling 경로 ===
      const { initThompsonState, loadThompsonState, saveThompsonState, sampleFromPosteriors, updatePosterior, adjustSigmaWithBKT } = await import('./thompson-sampling.js');
      const { computeSessionRewards } = await import('./reward.js');

      const tsState = loadThompsonState() ?? initThompsonState(previousVector);

      // 보상 계산 — dimensionSnapshot은 reward.ts가 이미 이벤트 시점 기반으로 설정
      // 단, reward.ts가 snapshot을 채우지 못한 경우 lastSample 또는 previousVector fallback
      const rewards = computeSessionRewards(events);
      for (const reward of rewards) {
        if (!reward.dimensionSnapshot || Object.keys(reward.dimensionSnapshot).length === 0) {
          // 얕은 복사: 참조 공유 방지. 원본 lastSample/previousVector가
          // 이후 coupled delta 등에 의해 변경되어도 snapshot이 오염되지 않도록 함.
          reward.dimensionSnapshot = { ...(tsState.lastSample ?? previousVector) };
        }
      }

      // 보상이 없으면 샘플링 건너뛰기 (랜덤 드리프트 방지)
      // NOTE: updatePosterior는 μ(REINFORCE)와 σ²(관측수 기반 감쇠)를 업데이트.
      // BKT 활성 시 σ²는 adjustSigmaWithBKT가 덮어씀 — 의도적 설계:
      // BKT σ²가 다음 사이클의 REINFORCE α로 사용되어, P(known) 낮으면 더 빠르게 학습.
      // σ²가 관측수 기반이므로 BKT 덮어쓰기 후에도 다음 updatePosterior에서 관측수 기반으로 재계산됨.
      if (rewards.length > 0) {
        for (const reward of rewards) {
          updatePosterior(tsState, reward);
        }
      }

      // BKT로 탐색 강도 조절 (optional)
      // adjustSigmaWithBKT는 σ²를 P(known)과 관측 수 기반으로 직접 설정 (conjugate σ²를 덮어씀)
      if (v2Config.preferenceTracing) {
        const { initPreferenceState, loadPreferenceStates, savePreferenceStates, updateFromPatterns, getPKnownMap, reEstimateParameters } = await import('./preference-tracer.js');
        const dims = Object.keys(previousVector);
        const prefStates = loadPreferenceStates() ?? initPreferenceState(dims);
        updateFromPatterns(prefStates, patterns, previousVector);
        // 관측 50+ 이후 BKT 파라미터 재추정 (EM-like)
        for (const state of Object.values(prefStates)) {
          reEstimateParameters(state);
        }
        adjustSigmaWithBKT(tsState, getPKnownMap(prefStates));
        savePreferenceStates(prefStates);
      }

      // 차원 상관관계 학습 + 적용 (optional)
      if (v2Config.dimensionCorrelation) {
        const { initCovarianceState, loadCovarianceState, saveCovarianceState, updateCovariance } = await import('./dimension-correlation.js');
        const dims = Object.keys(previousVector);
        const covState = loadCovarianceState() ?? initCovarianceState(dims);
        // 학습: 각 세션의 실제 차원 스냅샷으로 공분산 업데이트
        for (const reward of rewards) {
          updateCovariance(covState, reward.dimensionSnapshot);
        }
        saveCovarianceState(covState);
      }

      // 새 차원 벡터 샘플링 (보상 있을 때만, 없으면 현재값 유지)
      newVector = rewards.length > 0
        ? sampleFromPosteriors(tsState)
        : { ...previousVector };

      // 차원 상관 coupled delta 적용 (샘플링 후)
      if (v2Config.dimensionCorrelation && rewards.length > 0) {
        try {
          const { loadCovarianceState, computeCoupledDeltas } = await import('./dimension-correlation.js');
          const covState = loadCovarianceState();
          if (covState) {
            const primaryDelta: Record<string, number> = {};
            for (const [dim, val] of Object.entries(newVector)) {
              const diff = val - previousVector[dim];
              if (Math.abs(diff) > 0.001) primaryDelta[dim] = diff;
            }
            const coupled = computeCoupledDeltas(covState, primaryDelta);
            for (const [dim, delta] of Object.entries(coupled)) {
              newVector[dim] = Math.max(0, Math.min(1, (newVector[dim] ?? 0.5) + delta));
            }
          }
        } catch (e) { log.debug('coupled delta 적용 실패', e); }
      }

      saveThompsonState(tsState);
    } else {
      // === v1 EMA 경로 (fallback) ===
      newVector = applySmoothedAdjustments(previousVector, adjustments);
    }

    // v2 보상 수집 (TS 비활성 시만 — TS 경로에서는 이미 계산됨)
    // 보상 데이터를 저장하여 향후 OPRO 통합 시 활용 가능하도록 함
    if (v2Config.rewardCollection && !v2Config.thompsonSampling) {
      try {
        const { computeSessionRewards } = await import('./reward.js');
        const collectedRewards = computeSessionRewards(events);
        if (collectedRewards.length > 0) {
          const rewardHistoryPath = path.join(os.homedir(), '.compound', 'lab', 'reward-history.json');
          const existing = safeReadJSON<Array<{ timestamp: string; sessionId: string; reward: number }>>(rewardHistoryPath, []);
          const newEntries = collectedRewards.map(r => ({
            timestamp: r.timestamp,
            sessionId: r.sessionId,
            reward: r.reward,
          }));
          const merged = [...existing, ...newEntries].slice(-200); // 최근 200건 유지
          atomicWriteJSON(rewardHistoryPath, merged, { pretty: true });
        }
      } catch (e) { log.debug('보상 수집 실패', e); }
    }
    const changed = hasVectorChanged(previousVector, newVector);

    if (changed) {
      // Update profile dimensions
      profile.dimensions = newVector as typeof profile.dimensions;

      // Save updated profile
      saveForgeProfile(profile, GLOBAL_FORGE_PROFILE);

      // 5. Record evolution history
      const record: EvolutionRecord = {
        timestamp: new Date().toISOString(),
        adjustments,
        previousVector,
        newVector,
        eventWindowDays: windowDays,
        totalEventsAnalyzed: events.length,
      };
      const history = loadEvolutionHistory();
      history.push(record);
      // Keep last 100 records
      if (history.length > 100) {
        history.splice(0, history.length - 100);
      }
      saveEvolutionHistory(history);

      // 6. Re-generate harness config and record snapshot
      try {
        await regenerateHarnessConfig(profile);
      } catch (e) {
        log.debug('Failed to regenerate harness config', e);
      }

      // 7. Forge v2 투명성 알림 + GC (optional)
      if (v2Config.transparencyNotifications) {
        try {
          const { createChangeNotification, cleanOldNotifications } = await import('./transparency.js');
          const reasons: Record<string, string> = {};
          for (const adj of adjustments) {
            reasons[adj.dimension] = adj.evidence;
          }
          createChangeNotification(previousVector, newVector, reasons);
          cleanOldNotifications(30); // 30일 이상 알림 정리
        } catch (e) { log.debug('투명성 알림 실패', e); }
      }

      // 8. Track this auto-learn event in lab
      track('auto-evolve', 'system', {
        adjustmentCount: adjustments.length,
        eventsAnalyzed: events.length,
        dimensions: Object.keys(newVector)
          .filter(k => previousVector[k] !== newVector[k])
          .map(k => `${k}: ${previousVector[k]?.toFixed(3)} -> ${newVector[k]?.toFixed(3)}`),
      });
    }

    // 8. Save last evolve info
    saveLastEvolveInfo({
      timestamp: new Date().toISOString(),
      eventsAnalyzed: events.length,
      adjustmentCount: changed ? adjustments.length : 0,
      dryRun: false,
    });

    return {
      changed,
      adjustments,
      patterns,
      previousVector,
      newVector,
      totalEventsAnalyzed: events.length,
    };
  } catch (e) {
    log.debug('Evolution cycle failed', e);
    return {
      changed: false,
      adjustments: [],
      patterns: [],
      previousVector: null,
      newVector: null,
      totalEventsAnalyzed: 0,
      reason: `Error: ${e instanceof Error ? e.message : String(e)}`,
    };
  }
}

/**
 * Check if auto-learn should run (called from harness startup).
 * Conditions:
 * - At least MIN_HOURS_BETWEEN_RUNS since last run
 * - At least MIN_EVENTS_THRESHOLD new events since last run
 */
export function shouldAutoLearnRun(): boolean {
  try {
    const lastInfo = loadLastEvolveInfo();
    if (!lastInfo) return true; // Never ran before

    const lastRunMs = new Date(lastInfo.timestamp).getTime();
    const hoursSinceLastRun = (Date.now() - lastRunMs) / (1000 * 60 * 60);
    if (hoursSinceLastRun < MIN_HOURS_BETWEEN_RUNS) return false;

    // Check if enough new events accumulated
    const events = readEvents(lastRunMs);
    return events.length >= MIN_EVENTS_THRESHOLD;
  } catch (e) {
    log.debug('Failed to check auto-learn eligibility', e);
    return false;
  }
}

/**
 * Run auto-learn if conditions are met (non-blocking, error-safe).
 * Called from harness startup.
 * Returns EvolveResult if a cycle ran, null if skipped.
 */
export async function tryAutoLearn(): Promise<EvolveResult | null> {
  try {
    if (!shouldAutoLearnRun()) return null;
    return await runEvolveCycle(false);
  } catch (e) {
    // Never crash harness startup
    log.debug('Auto-learn failed silently', e);
    return null;
  }
}

// ---------------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------------

function hasVectorChanged(
  prev: Record<string, number>,
  next: Record<string, number>,
): boolean {
  for (const key of Object.keys(prev)) {
    if (Math.abs((prev[key] ?? 0) - (next[key] ?? 0)) > 0.001) {
      return true;
    }
  }
  return false;
}

/**
 * Re-generate harness config from updated profile and create snapshot.
 */
async function regenerateHarnessConfig(
  profile: { dimensions: Record<string, number> },
): Promise<void> {
  try {
    const { generateConfig } = await import('../forge/generator.js');
    const { createSnapshot } = await import('./history.js');

    // Generate new derived config (validates the profile still works)
    generateConfig(profile.dimensions as never);

    // Create a snapshot to record the auto-evolution
    createSnapshot('auto-evolve');

    log.debug('Harness config regenerated after auto-evolution');
  } catch (e) {
    log.debug('Config regeneration failed', e);
  }
}
